<?php
// Authors:      Luis Fernando
//               Kevin Legarreta
//               David J. Ortiz Rivera
//               Enrique Rodriguez
//
//  File: PasswordRequestHandler.php
//  Description: Manages the reset password requests generated by the user.
//  Created by Los Duendes Malvados.
//  Copyright © 2018 Los Duendes Malvados. All rights reserved.

class PasswordRequestHandler extends Model {
	/**
	 * Default constructor. Calls the parent constructor, initializing the database.
	 */	
	public function __construct() {
		parent::__construct();
	}
	/**
	 * Checks if request is valid. Returns true if request is in the database.
	 */
	public function is_legit_request($request) {
		$query = "SELECT * 
			      FROM reset_password_requests
		          WHERE request_id = (\"$request\")";
		if(!$response = $this->database->query($query)) {
			echo "No Response";
		}
		
		if(!$response->num_rows) {
			return true;
		}
		
		return false;
	}
	/**
	 * Deletes a given reset password request.
	 */
	public function delete_request($request) {
		$query = "DELETE FROM reset_password_requests
			  WHERE request_id='{$request}'";
		return $this->database->query($query);
	}
}